apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
commonLabels:
  # https://github.com/GoogleContainerTools/skaffold/issues/3219
  skaffold.dev/run-id: static
  app.kubernetes.io/managed-by: skaffold
resources:
  - genesisconf.yaml
  - nodeconf.yaml
  - service.yaml
  - statefulset.yaml
