apiVersion: v1
kind: ConfigMap
metadata:
  name: queth-nodeconfig
  labels:
    app.kubernetes.io/name: queth-nodeconfig
    app.kubernetes.io/part-of: queth

data:
  nodeconf.json: |-
    {
        "chain_blob_path": "ledger",
        "genesis_blob":"ledger/queth-genesis.json",
        "static_nodes_blob": "ledger/static-nodes.json",
        "key": "/var/lib/quorum/nodekey",
        "dir": "/var/lib/quorum/node",
        "bucket": "quorumpreempt-2c54a054-d234-d92c-e089-d7e0c61a23db",
        "bind": "127.0.0.1",
        "address": "127.0.0.1",
        "port": 30303,
        "rpcport": 8545,
        "wsport": 8546,
        "raftport": 50400
    }
