apiVersion: v1
kind: ServiceAccount
metadata:
  name: quorum-genesis-sa
  # be explicit, because the GCP SA binding only works for the declared ns
  namespace: queth
  annotations:
    iam.gke.io/gcp-service-account: quorum-genesis-sa@quorumpreempt.iam.gserviceaccount.com
automountServiceAccountToken: true
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: quorum-node-sa
  namespace: queth
  annotations:
    iam.gke.io/gcp-service-account: quorum-node-sa@quorumpreempt.iam.gserviceaccount.com
automountServiceAccountToken: true
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: quorum-membership-sa
  namespace: queth
  annotations:
    iam.gke.io/gcp-service-account: quorum-membership-sa@quorumpreempt.iam.gserviceaccount.com
automountServiceAccountToken: true
