apiVersion: v1
kind: Service
metadata:
  name: queth
  labels:
    app: queth
spec:
  ports:
  - name: tcp-peer
    port: 30303
  - name: tcp-rpc
    port: 8545
  - name: tcp-wsock
    port: 8546
  - name: tcp-raft
    port: 50400
  clusterIP: None
  selector:
    app: queth
