apiVersion: skaffold/v2beta6
kind: Config
metadata:
  name: quorumpreempt
build:
  artifacts:
  - image: eu.gcr.io/quorumpreempt-284308/adder-builder
    context: adder
    docker:
      dockerfile: Dockerfile-builder
  - image: eu.gcr.io/quorumpreempt-284308/adder
    context: adder
    docker:
      dockerfile: Dockerfile
  - image: eu.gcr.io/quorumpreempt-284308/shcurl
    docker:
      dockerfile: shcurl/Dockerfile
  - image: eu.gcr.io/quorumpreempt-284308/nginx-web
    context: nginx-alpine
  - image: eu.gcr.io/quorumpreempt-284308/quethraft-init
    context: queth
    sync: {}
    docker:
      dockerfile: Dockerfile-init
  - image: eu.gcr.io/quorumpreempt-284308/queth
    context: queth
    sync: {}
    docker:
      dockerfile: Dockerfile
deploy:
  kubectl:
    manifests:
    - k8s/dnsutils/dnsutils.yaml
  kustomize:
    paths:
    - k8s/dev-example
