apiVersion: skaffold/v2beta5
kind: Config
metadata:
  name: quorum-gcp-preemptible
build:
  artifacts:
  - image: eu.gcr.io/quorumpreempt/nginx-web
    context: nginx-alpine
  - image: eu.gcr.io/quorumpreempt/quethraft-init
    context: queth
    sync:
      infer:
    docker:
      dockerfile:
        Dockerfile-init
  - image: eu.gcr.io/quorumpreempt/queth
    context: queth
    sync:
      infer:
    docker:
      dockerfile:
        Dockerfile

deploy:
  kubectl:
    manifests:
    - k8s/kubeip/clusterrole.yaml
    - k8s/kubeip/configmap.yaml
    - k8s/kubeip/deployment.yaml
    - k8s/nginx-web/namespace.yaml
    - k8s/nginx-web/deployment.yaml
    - k8s/nginx-web/service.yaml
    - k8s/traefik/configmap.yaml
    - k8s/traefik/namespace.yaml
    - k8s/traefik/serviceaccount.yaml
    - k8s/traefik/deployment.yaml
    - k8s/traefik/resource.yaml
    - k8s/traefik/route.yaml
    - k8s/queth/genesisconf.yaml
    - k8s/queth/nodeconf.yaml
    - k8s/queth/statefulset.yaml
    - k8s/queth/service.yaml

profiles:
  - name: dnsutils
    deploy:
      kubectl:
        manifests:
        - k8s/dnsutils/dnsutils.yaml

  - name: queth
    deploy:
      kubectl:
        manifests:
        - k8s/queth/genesisconf.yaml
        - k8s/queth/nodeconf.yaml
        - k8s/queth/statefulset.yaml
        - k8s/queth/service.yaml
