apiVersion: skaffold/v2beta5
kind: Config
metadata:
  name: quorum-gcp-preemptible
build:
  artifacts:
  - image: eu.gcr.io/quorumpreempt/adder-builder
    context: adder
    docker:
      dockerfile:
        Dockerfile-builder
  - image: eu.gcr.io/quorumpreempt/adder
    context: adder
    docker:
      dockerfile:
        Dockerfile
  - image: eu.gcr.io/quorumpreempt/shcurl
    docker:
      dockerfile:
        shcurl/Dockerfile
  - image: eu.gcr.io/quorumpreempt/nginx-web
    context: nginx-alpine
  - image: eu.gcr.io/quorumpreempt/quethraft-init
    context: queth
    sync:
      infer:
    docker:
      dockerfile:
        Dockerfile-init
  - image: eu.gcr.io/quorumpreempt/queth
    context: queth
    sync:
      infer:
    docker:
      dockerfile:
        Dockerfile

deploy:
  kustomize:
    paths:
      - k8s/ledger/bases
      - k8s/caas/bases
      - k8s/north/bases

profiles:

  - name: north
    deploy:
      kustomize:
        paths:
          - k8s/north/bases
  - name: caas
    deploy:
      kustomize:
        paths:
          - k8s/caas/bases
  - name: ledger
    deploy:
      kustomize:
        paths:
          - k8s/ledger/bases


  - name: dnsutils
    deploy:
      kubectl:
        manifests:
        - k8s/dnsutils/dnsutils.yaml
