apiVersion: skaffold/v2beta5
kind: Config
metadata:
  name: quorum-gcp-preemptible

deploy:
  kustomize:
    paths:
      # - k8s/bases
      - k8s/dev-example
  kubectl:
    manifests:
      - k8s/dnsutils/dnsutils.yaml

build:
  artifacts:
  - image: eu.gcr.io/ledger-2/adder-builder
    context: adder
    docker:
      dockerfile:
        Dockerfile-builder
  - image: eu.gcr.io/ledger-2/adder
    context: adder
    docker:
      dockerfile:
        Dockerfile
  - image: eu.gcr.io/ledger-2/shcurl
    docker:
      dockerfile:
        shcurl/Dockerfile
  - image: eu.gcr.io/ledger-2/nginx-web
    context: nginx-alpine
  - image: eu.gcr.io/ledger-2/quethraft-init
    context: queth
    sync:
      infer:
    docker:
      dockerfile:
        Dockerfile-init
  - image: eu.gcr.io/ledger-2/queth
    context: queth
    sync:
      infer:
    docker:
      dockerfile:
        Dockerfile


