# https://taskfile.dev
version: '2'

vars:
  MAX_NODE_IDX: 2

tasks:

  nodekeys:
    desc: ensure all node secrets exist in gcp
    cmds:
      - |
        for i in $(seq 0  {{.MAX_NODE_IDX}})
        do
          tools/secrets.sh nodekey qnode-$i-
          tools/secrets.sh wallet qnode-$i-wallet-
        done
    silent: true
