# https://taskfile.dev
version: '2'

vars:
  MAX_NODE_IDX: 2

tasks:

  nodekeys:
    desc: ensure all node secrets exist in gcp
    cmds:
      - |
        for i in $(seq 0  {{.MAX_NODE_IDX}})
        do
          tools/secrets.sh nodekey qnode-$i-
          tools/secrets.sh wallet qnode-$i-wallet-
        done
    silent: true

  tf-import-secrets:
    desc: import secret manager secrets (not values) into terraform
    dir: cluster
    cmds:
      - |
        for i in $(seq 0 {{.MAX_NODE_IDX}}); do
          for kind in key enode wallet-address wallet-key wallet-password; do
            terraform import \
              module.cluster.google_secret_manager_secret.qnode[\"qnode-$i-$kind\"] \
              projects/quorumpreempt/secrets/qnode-$i-$kind
          done
        done
    silent: true

  tf-rmstate-secrets:
    desc: remove secret manager secret resources DOES NOT delete keys
    dir: cluster
    cmds:
      - |
        for i in $(seq 0 {{.MAX_NODE_IDX}}); do
          for kind in key enode wallet-address wallet-key wallet-password; do
          terraform state rm \
            module.cluster.google_secret_manager_secret.qnode[\"qnode-$i-$kind\"]
          done
        done
    silent: true
