apiVersion: apps/v1
kind: Deployment
metadata:
  name: adder
  labels:
    app.kubernetes.io/name: adder
    app.kubernetes.io/part-of: adder
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: adder
      app.kubernetes.io/part-of: adder
  template:
    metadata:
      labels:
        app.kubernetes.io/name: adder
        app.kubernetes.io/part-of: adder
    spec:
      serviceAccountName: quorum-node-sa
      volumes:
      - name: wallet
        emptyDir: {}
      initContainers:
      - name: adderinit
        image: eu.gcr.io/quorumpreempt/shcurl
        command:
          - sh
        args:
          - -cx
          - |
            TOKEN=$(curl -s -H 'Metadata-Flavor: Google' \
              http://metadata/computeMetadata/v1/instance/service-accounts/default/token | \
              jq -r .access_token)
            [ -n "$TOKEN" ] || exit 1
            curl -sS "https://secretmanager.googleapis.com/v1/projects/quorumpreempt/secrets/qnode-0-wallet-key/versions/latest:access" \
              --request "GET" \
              --header "authorization: Bearer ${TOKEN}" \
              --header "content-type: application/json" | \
              jq -r .payload.data | base64 -d > /service/wallet/key
            [ $(wc -c < /service/wallet/key) == 32 ] || exit 1
        volumeMounts:
        - mountPath: /service/wallet
          name: wallet

      containers:
      - name: "adder"
        image: eu.gcr.io/quorumpreempt/adder
        ports:
          - name: grpc-port
            containerPort: 9091
        env:
          - name: PORT
            value: "9091"
          - name: ETH_RPC
            value: http://queth-1.queth:8545
          - name: WALLET_KEY
            value: /service/wallet/key
        command:
          - /service/adder-service

        readinessProbe:
          exec:
            command: ["/service/grpc_health_probe", "-service=readiness", "-addr=:9091"]
          initialDelaySeconds: 10
          timeoutSeconds: 1
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 3
        volumeMounts:
        - mountPath: /service/wallet
          name: wallet
