apiVersion: v1
kind: Service
metadata:
  name: adder
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      name: grpc-port
      port: 9091
      targetPort: 9091
  selector:
    app.kubernetes.io/name: adder
    app.kubernetes.io/part-of: adder
