- op: replace
  # patching env this way, by assuming list indices, is a recipe for disaster.
  # For env vars that are known before deployment, like project id, seed
  # templates (sed, envsubst, jsonnet) are the only sane approach.  ConfigMap's
  # are needlessly complicated for this. The targetting makes it possible to
  # write validation tooling, but it would still need to be written.
  path: /spec/template/spec/initContainers/0/env/0
  value:
    name: PROJECT_ID
    value: ledger-2
