# This should be edited or used as starting point for your own
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - ../bases

images:
  - name: eu.gcr.io/quorumpreempt/shcurl
    newName: eu.gcr.io/ledger-2/shcurl
  - name: eu.gcr.io/quorumpreempt/adder
    newName: eu.gcr.io/ledger-2/adder
  - name: eu.gcr.io/quorumpreempt/quethraft-init
    newName: eu.gcr.io/ledger-2/quethraft-init
  - name: eu.gcr.io/quorumpreempt/nginx-web
    newName: eu.gcr.io/ledger-2/nginx-web

patchesStrategicMerge:
  - overlay.yaml

patchesJson6902:
# These could probably be done in the overlay too, but I wanted an example of
# the patch style and these are less verbose this way.
- target:
    group: traefik.containo.us
    version: v1alpha1
    kind: IngressRoute
    namespace: caas
    name: ingressroutetls
  path: caas-adder-route-patch.yaml
- target:
    group: traefik.containo.us
    version: v1alpha1
    kind: IngressRoute
    namespace: nginx-web
    name: ingressroutetls
  path: north-nginx-route-patch.yaml
