# main overlay - retained for comparison with .jsonnet approach
apiVersion: apps/v1
kind: Deployment
metadata:
  name: adder
spec:
  template:
    spec:
      initContainers:
        - name: adderinit
          env:
            - name: PROJECT_ID
              value: ledger-2
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: node
spec:
  template:
    spec:
      initContainers:
        - name: quethinit
          env:
            - name: BUCKET
              value: ledger-2-2c54a054-d234-d92c-e089-d7e0c61a23db
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: traefik-web
spec:
  template:
    spec:
      containers:
        - name: traefik
          env:
            - name: ACME_EMAIL
              value: robinbryce@gmail.com
