// NOTICE: To use this file after terraform deploying you need to first
// generate ledger.tf.json
//
// ledger.tf.out.json is generated by running `terraform output -json`
// standing in the tf/ledger directory
local overlaysaTemplate = import 'overlay.sa.jsonnet.TEMPLATE';
local overlayenvTemplate = import 'overlay.env.jsonnet.TEMPLATE';
local ledgertfout = import 'ledger.tf.out.json';
overlaysaTemplate(ledgertfout) +
overlayenvTemplate(ledgertfout, 'robinbryce@gmail.com')
