apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: ingressroutetls
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`queth.preempt.robinbryce.me`) && PathPrefix(`/static`)
      kind: Rule
      services:
        - name: nginx-web
          port: 80

  tls:
    certResolver: letsencrypt
    #domains:
    #  - main: "*.robinbryce.me"
    #    #sans: "*.robinbryce.me"
    #
