ARG BASE_TAG=2.6.0

FROM quorumengineering/quorum:${BASE_TAG}
ARG REQUIREMENTS_TXT=requirements.txt

# Set the location for pip3 install --user
ENV PYTHONUSERBASE="/service"
WORKDIR $PYTHONUSERBASE
COPY ${REQUIREMENTS_TXT} .

ENV PATH="/service/bin:$PATH"

RUN \
  apk add --no-cache \
    python3 && \
  pip3 install --user -r ${REQUIREMENTS_TXT}

COPY commoncli.py /service/
COPY quethraft.py /service/
ENTRYPOINT ["/usr/bin/python3"]
ENV PYTHONPATH="/service"
ENV PYTHONUNBUFFERED=1
CMD ["quethraft.py", "--nodedir", "/var/lib/quorum/node"]
