apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: traefik
resources:
  - namespace.yaml
  - serviceaccount.yaml
  - clusterrole.yaml
  - resource.yaml
  - deployment.yaml
  - service.yaml
