apiVersion: v1
kind: ServiceAccount
metadata:
  name: dns01solver-sa
  namespace: traefik
  annotations:
    iam.gke.io/gcp-service-account: dns01solver-sa@quorumpreempt.iam.gserviceaccount.com
automountServiceAccountToken: true
