apiVersion: apps/v1

kind: Deployment
metadata:
  name: adder
  labels:
    app: adder
spec:
  replicas: 1
  selector:
    matchLabels:
      app: adder
  template:
    metadata:
      labels:
        app: adder
    spec:
      nodeSelector:
        cloud.google.com/gke-nodepool: work-pool
      serviceAccountName: quorum-client-sa
      volumes:
      - name: wallet
        emptyDir: {}
      initContainers:
      - name: adderinit
        image: eu.gcr.io/quorumpreempt/shcurl
        command:
          - sh
        env:
          # It seems for kustomize to patch the env, it has to *assume* the
          # indexes of variables. So take care if casually moving things
          # around - it is essentially a change of public interface.
          - name: PROJECT_ID
            # PROJECT_ID rather than GCP_PROJECT_ID so as not to collide with
            # magic google var names
            value: quorumpreempt
        args:
          - -cx
          - |
            TOKEN=$(curl -s -H 'Metadata-Flavor: Google' \
              http://metadata/computeMetadata/v1/instance/service-accounts/default/token | \
              jq -r .access_token)
            [ -n "$TOKEN" ] || exit 1
            curl -sS "https://secretmanager.googleapis.com/v1/projects/${PROJECT_ID}/secrets/qnode-0-wallet-key/versions/latest:access" \
              --request "GET" \
              --header "authorization: Bearer ${TOKEN}" \
              --header "content-type: application/json" | \
              jq -r .payload.data | base64 -d > /service/wallet/key
            [ $(wc -c < /service/wallet/key) == 32 ] || exit 1
        volumeMounts:
        - mountPath: /service/wallet
          name: wallet

      containers:
      - name: "adder"
        image: eu.gcr.io/quorumpreempt/adder
        ports:
          - name: grpc-port
            containerPort: 9091
        env:
          #- name: GOTRACEBACK
          #  value: all
          - name: PORT
            value: "9091"
          - name: ETH_RPC
            value: http://node-1.queth.queth:8545
          - name: WALLET_KEY
            value: /service/wallet/key
          #- name: CONTRACT_ADDRESS
          #  value: 0x2976ab0117675374E65B50179A224aE7d7599ce3
        command:
          - /service/adder-service

        readinessProbe:
          exec:
            command: ["/service/grpc_health_probe", "-service=readiness", "-addr=:9091"]
          initialDelaySeconds: 10
          timeoutSeconds: 1
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 3
        volumeMounts:
        - mountPath: /service/wallet
          name: wallet
