apiVersion: v1
kind: ServiceAccount
metadata:
  name: quorum-client-sa
  namespace: caas
  annotations:
    iam.gke.io/gcp-service-account: quorum-client-sa@ledger-2.iam.gserviceaccount.com
automountServiceAccountToken: true
