apiVersion: v1
kind: ServiceAccount
metadata:
  name: kubeip-sa
  # be explicit, because the GCP SA binding only works for the declared ns
  namespace: kube-system
  annotations:
    iam.gke.io/gcp-service-account: kubeip-sa@quorumpreempt.iam.gserviceaccount.com
automountServiceAccountToken: true
