apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: qnode
  name: qnode-nodeconfig
  namespace: default
data:
  nodeconf.json: |-
    {
      "node": {
        "secretnames": "qnode-{number}-{kind}",
        "genesis_blob":"quorumpreempt/chain1/qnode-genesis.json",
        "static_nodes_blob": "quorumpreempt/chain1/static-nodes.json",
        "member_blob": "quorumpreempt/chain1/member-{enode}.json",
        "key": "/var/lib/quorum/nodekey",
        "dir": "/var/lib/quorum/node",
        "bucket": "quorumpreempt-cluster.g.buckets.thaumagen.com",
        "bind": "127.0.0.1",
        "ipaddress": "127.0.0.1",
        "port": 30303,
        "rpcport": 8545,
        "wsport": 8546,
        "raftport": 50400
      }
    }
