apiVersion: v1
kind: Service
metadata:
  name: qnode
  labels:
    app: qnode
spec:
  ports:
  - name: tcp-peer
    port: 30303
  - name: tcp-rpc
    port: 8545
  - name: tcp-wsock
    port: 8546
  - name: tcp-raft
    port: 50400
  clusterIP: None
  selector:
    app: qnode
    #app.kubernetes.io/name: qnode
    #app.kubernetes.io/part-of: qnode
